# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Based on the default minimal mistakes config file at:
# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: 'en-US'
title: Greg Ferland
title_separator: '|'
description: |
  Personal and portfolio website for Greg Ferland, Software Engineer.
  Skier. Runner. Mainer. Currently living in Boston, MA.
url: https://www.gmferland.com
baseurl: # the subpath of your site, e.g. "/blog"
repository: gmferland/gmferland.com
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Social sharing
og_image: /assets/images/bio-photo.jpg

# Analytics
analytics:
  provider: google
  google:
    tracking_id: 'UA-116117867-1'
    anonymize_ip: false # (default)

# Site author
author:
  name: 'Greg Ferland'
  email: gmferland@gmail.com
  avatar: '/assets/images/bio-photo.jpg'
  bio: Don't let perfect be the enemy of good.
  location: 'Boston, MA'
  links:
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/greg-ferland-4563b8b6/'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/gmferland'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/gmferland'
    - label: 'Instagram'
      icon: 'fab fa-fw fa-instagram'
      url: 'https://www.instagram.com/gmferland/'

footer:
  links:
#    - label: 'Twitter'
#      icon: 'fab fa-fw fa-twitter-square'
#      url: 'https://twitter.com/'
#    - label: 'GitHub'
#      icon: 'fab fa-fw fa-github'
#      url: 'https://github.com/'
#    - label: 'Instagram'
#      icon: 'fab fa-fw fa-instagram'
#      url: 'https://instagram.com/'

collections:
  portfolio:
    output: true,
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ''
      type: portfolio
    values:
      layout: portfolio
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
